Here I am testing out how array broadcasting works in numpy. I want to make 2D arrays out of 1D arrays without looping, but by using broadcasting.

For examle, I want to make an array arr_3 out of arr_1 and arr_2 such that arr_3[i][j] = arr_1[i] * arr_2[j] (or some other definition, but we start with this). The point of this is to more efficiently implement the formulas I need for the geonu stuff (survival probability etc) so I don't need to use nested loops and I can make things more efficient.

In [1]:
import numpy as np

In [2]:
arr_1 = np.array([1, 2, 3])
arr_2 = np.array([4, 5, 6])

In [3]:
reshaped_arr_1 = arr_1[:, np.newaxis] 


In [5]:
print(reshaped_arr_1) # it becomes a 2D column vector

[[1]
 [2]
 [3]]


In [6]:
reshaped_arr_2 = arr_2[np.newaxis, :] # it becomes a 2D row vector 

In [7]:
print(reshaped_arr_2)

[[4 5 6]]


In [8]:
arr_3 = reshaped_arr_1 * reshaped_arr_2
print(arr_3)

[[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]


In [ ]:
# can do this for more complicated functions as well



More generally, broadcasting can replace for loops in a much more efficient way. This is how to figure out the equivalence between a for loop and an operation between broadcasted arrays.

To check if two arrays of dimentsions (a_n, a_{n-1}, ... a_1) and (b_m, ... b_1) are compatible, do this:

1) Move the tuple of dimensions of the array with fewer dimensions to the left and fill in with ones to the right until the number of dimensions is the same. If the a one was shorter, this means the dimensions of the new arrays will be (1, 1, ..., 1, a_n,..., a_1) and (b_m, ... b_1)
2) We go one by one looking at the dimensions to check if they 'match'. There is the match eiher if they are the same, or if one of them is equal to 1

Now, if we were working with arrays of these dimensions, there would be an index for each dimension. If the dimension is one, the only valid index would be 0. So if we calculate a function of "ordinary" maths operations (multiplication, addition, etc) f(x, y), if x and y are our arrays, and let's say z is the result, we'll have, for example:

$$z[i, j] = f( x[i, j], y[i, j])$$

If we look at the index corresponding to a dimension of 1, that can only be 0; so if x only had dimension corresponding to index j initially and we broadcasted it to match y, that will mean:

$$z[i, j] = f( x[0, j], y[i, j])$$

If dimension j was initially 1 for y, this will further imply:

$$z[i, j] = f( x[0, j], y[i, 0])$$

In [10]:
print(np.shape(reshaped_arr_1))
print(np.shape(reshaped_arr_2))

(3, 1)
(1, 3)


Note: when you use np.newaxis in array indexing, it adds a new axis(dimension) with length one to the array.